version: '2'
services: 
  db:
    image: mongo:3.4
    ports:
      - "27017:27017"
    command: "--smallfiles --logpath=/dev/null"
  web:
    build: .
    ports: 
     - "80:8000"
    links: 
     - db
